workflows:
  android-workflow:
    name: AQNIET Android Build (APK + AAB)
    max_build_duration: 60

    environment:
      flutter: stable
      java: 17
      android_signing:
        - aqniet_keystore

    scripts:
  - name: Flutter clean
    script: flutter clean

  - name: Get Flutter packages
    script: flutter pub get

  - name: Generate launcher icons
    script: dart run flutter_launcher_icons

  - name: Analyze
    script: flutter analyze

    artifacts:
      - build/app/outputs/bundle/release/*.aab
      - build/app/outputs/flutter-apk/*.apk
      - build/**/mapping.txt
