workflows:
  android-workflow:
    name: AQNIET Android Build (APK + AAB)
    max_build_duration: 60

    environment:
      flutter: stable
      java: 17
      android_signing:
        - aqniet_keystore

    scripts:
      - name: Get Flutter packages
        script: flutter pub get

      - name: Analyze
        script: flutter analyze

      - name: Build AAB (release)
        script: flutter build appbundle --release

      - name: Build APK (release)
        script: flutter build apk --release

    artifacts:
      - build/app/outputs/bundle/release/*.aab
      - build/app/outputs/flutter-apk/*.apk
      - build/**/mapping.txt
